USE [INVEST]
GO

CREATE TABLE TB_CLIENTS (
    CLIENT_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NAME NVARCHAR(1000) NOT NULL,
    USERNAME NVARCHAR(100) NOT NULL,
	PASSWORD NVARCHAR(20) NOT NULL
);

CREATE TABLE TB_ACCOUNTS_CLIENTS (
    ACCOUNT_CLIENT_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ACCOUNT NVARCHAR(10) NOT NULL,
	CLIENT_ID INT NOT NULL,
	BALANCE NUMERIC(15,2) NOT NULL,
	CONSTRAINT FK_ACCOUNT_CLIENTS FOREIGN KEY (CLIENT_ID)
    REFERENCES TB_CLIENTS(CLIENT_ID),
);

CREATE TABLE TB_PRODUCTS (
    PRODUCT_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    BOND_ASSET NVARCHAR(200) NOT NULL,
    INDEXADOR NVARCHAR(500) NOT NULL,
	TAX NUMERIC(15,1) NOT NULL,
	ISSUER_NAME NVARCHAR(1000) NOT NULL,
	UNIT_PRICE BIGINT NOT NULL,
	STOCK BIGINT NOT NULL
);
